project:
  type: website
  output-dir: docs

website:
  title: "Resume for Mohit Shrestha"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

